language: java
branches:
  only:
  - master
jdk:
- oraclejdk8

script:
- ./gradlew check test integrationTest jacoco
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
