spring:
  application:
    name: storeroom-app
  main:
    banner-mode: "OFF"
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximumPoolSize: 30
      poolName: storeroom
      minimumIdle: 5